import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import localFont from "next/font/local"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Dev Archive",
    description: "Generated by create next app",
}

const pretendard = localFont({
    src: "../fonts/pretendard/PretendardVariable.woff2",
    weight: "100 900",
    display: "swap",
    variable: "--font-pretendard",
})

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="ko" className={`${pretendard.variable} ${geistSans.variable} ${geistMono.variable}`}>
        <body className="antialiased font-sans">
        {children}
        </body>
        </html>
    )
}